In [2]:
import numpy as np
np.set_printoptions(precision=None, suppress=True)

# Save Finalized Training Data 

In [1]:
# Load s2 data
pix_3darray = np.load('training-data-draft.npy')
pix_3darray.shape
# pix_3darray[:, 0, 0]

NameError: name 'np' is not defined

In [3]:
# Load cdl data
cdl_array = np.load('cdl-array.npy')
np.unique(cdl_array)

array([  1,   2,   3,   4,   5,   6,  10,  24,  26,  27,  28,  29,  31,
        36,  37,  44,  46,  48,  57,  59,  61,  67,  74, 111, 121, 122,
       123, 124, 131, 141, 142, 143, 152, 176, 190, 195, 236, 238, 240],
      dtype=uint8)

In [4]:
# Prep cdl data with my groupings
import pandas as pd
df = pd.read_csv('CDL Numerical Codes + New Groups.csv')
grps_dict = {
    'old': df['CDL Value'].tolist(),
    'new': df['New Value'].tolist()
} 

In [5]:
for count, value in enumerate(grps_dict['old']):
    cdl_array[cdl_array == value] = grps_dict['new'][count]

np.unique(cdl_array, return_counts=True)

(array([  1,   2,   3,   5,   6,  22,  44,  88, 200], dtype=uint8),
 array([ 70849,  17797,  61282, 167041,   3892,  31582,  25911,  84807,
         23409]))

In [6]:
rows, cols = np.mgrid[slice(pix_3darray.shape[1]), slice(pix_3darray.shape[2])]

In [8]:
import itertools as it

pix_1d_rows = []
for col in range(0, 294):    
    for row in range(0, 1655):
        s2 = pix_3darray[:, row, col]
        cdl_val = [cdl_array[row, col]]
        out = np.append(s2, cdl_val, axis=0)
        # print(out.shape)
        pix_1d_rows.append(out)

len(pix_1d_rows)

486570

In [1]:
pix_2darray_final = np.stack(pix_1d_rows, axis=0)
# np.unique(pix_2darray_final, return_counts=True)
# np.save('training-data-final.npy', pix_2darray_final)

NameError: name 'np' is not defined

In [6]:
pix_2darray_final = np.load('nparray-data/training-data-final.npy')
pix_2darray_final[0:10]

array([[ 0.05303108,  0.07653115,  0.12031347,  0.14591208,  0.1980508 ,
         0.24477509,  0.26381692,  0.29120672,  0.29395548,  0.29530075,
         0.3333842 ,  0.22538912,  0.0072    ,  0.09010772,  0.0005    ,
         0.01486296,  0.01228534,  0.00783781,  0.        ,  0.        ,
         0.        ,  0.03877578,  0.05913265,  0.0886443 ,  0.13022067,
         0.15269788,  0.16050163,  0.1716621 ,  0.19261067,  0.19268557,
         0.16521966,  0.1745361 ,  0.12069716,  0.0066    ,  0.07      ,
         0.0007    ,  0.0132751 ,  0.0090295 ,  0.00605597,  0.00027539,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0. 

# Save Finalized Testing Data

In [8]:
test_3darray = np.load('testing-data-draft.npy')
test_3darray.shape

(21, 331, 294)

In [ ]:
rows, cols = np.mgrid[slice(test_3darray.shape[1]), slice(test_3darray.shape[2])]

import itertools as it

test_1d_rows = []
for col in range(0, 294):    
    for row in range(0, 331):
        s2 = test_3darray[:, row, col]
        cdl_val = [cdl_array[row, col]]
        out = np.append(s2, cdl_val, axis=0)
        # print(out.shape)
        test_1d_rows.append(out)

len(test_1d_rows)

In [17]:
test_2darray_final = np.stack(test_1d_rows, axis=0)
test_2darray_final.shape

(97314, 24)

In [19]:
test_2darray_final[0:5]
# np.save('testing-data-final.npy', test_2darray_final)